### ISSUE TITLE
Error with custom image size parameters

### ISSUE THREAD

**Issue by icemanovich** [alyssaq/face_morpher#12]
When try to resize image to 16:9 proportion script gives me an error:

```
Traceback (most recent call last):
  File "facemorpher/morpher.py", line 183, in <module>
    args['--alpha'], args['--plot'])
  File "facemorpher/morpher.py", line 171, in morpher
    width, height, num_frames, fps, out_frames, out_video, alpha, plot)
  File "facemorpher/morpher.py", line 135, in morph
    src_face = warper.warp_image(src_img, src_points, points, size)
  File "/opt/face_morpher/facemorpher/warper.py", line 94, in warp_image
    process_warp(src_img, result_img, tri_affines, dest_points, delaunay)
  File "/opt/face_morpher/facemorpher/warper.py", line 59, in process_warp
    result_img[y, x] = bilinear_interpolate(src_img, out_coords)
  File "/opt/face_morpher/facemorpher/warper.py", line 19, in bilinear_interpolate
    q11 = img[y0, x0]
IndexError: index 600 is out of bounds for axis 0 with size 600

```

Input images have 1920x1080px resolution. But morpher.py works with default size (500x600).

How to fix this?

**Comment by alyssaq** [comment]
Hi. Could you email me a sample image with this error so I can find and fix it? Thanks!
