### ISSUE TITLE
Averager error

### ISSUE THREAD

**Issue by AnaTomomi** [alyssaq/face_morpher#21]
Hi Alyssa,

I am trying to use the averager but I get the following error (MacOS with python2.7):

.../python/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
python facemorpher/averager.py --images=images
Traceback (most recent call last):
  File "facemorpher/averager.py", line 93, in <module>
    args['--out'], args['--plot'])
  File "facemorpher/averager.py", line 69, in averager
    result_images = np.zeros(images[0].shape, np.float32)
 
IndexError: list index out of range

Thank you!

**Comment by alyssaq** [comment]
It looks like it didnt find any valid face images in that folder.

**Comment by AnaTomomi** [comment]
Thanks for the answer Alyssa. Yes, the folder contains 4 images in .png format. The images contain faces with neutral expression and looking directly to the lens. Are there any other special requirements (e.g. size of the image) that I should check?

**Comment by alyssaq** [comment]
Could you pull the latest code from `master` and try again? I added some error handling and curious if it'll catch your case.
 If it doesnt, can you try running [face_verifier](https://github.com/alyssaq/face_verifier) to see if your images have a detectable face with openCV?
