### ISSUE TITLE
ImportError: No module named 'locator'

### ISSUE THREAD

**Issue by bozzmob** [alyssaq/face_morpher#24]
I tried using the project as a library.
Python 3.5, OpenCV 3.3, Ubuntu 16.04

I have images in the `imgs` folder.
Code-
```
(cv) ubuntu@ip:~/face_morpher_aslib$ cat fm.py 
import facemorpher
facemorpher.averager(['imgs/trump.jpg', 'imgs/madara.jpg'], plot=True)
```

But, when I try to run the program, I end up with the following error-
```
(cv) ubuntu@ip:~/face_morpher_aslib$ python fm.py 
Traceback (most recent call last):
  File "fm.py", line 1, in <module>
    import facemorpher
  File "/home/ubuntu/.virtualenvs/cv/lib/python3.5/site-packages/facemorpher/__init__.py", line 5, in <module>
    from .morpher import morpher, list_imgpaths
  File "/home/ubuntu/.virtualenvs/cv/lib/python3.5/site-packages/facemorpher/morpher.py", line 34, in <module>
    import locator
ImportError: No module named 'locator'
```

I also did a pip search, couldn't find the module.

```
(cv) ubuntu@ip:~/face_morpher_aslib$ pip search locator
resource-allocator (0.1.0)                        - Python Resource Allocation API
bareon-allocator (1.0.0.dev)                      - 
allocator (0.1.7)                                 - Optimally Allocate Geographically Distributed Tasks
celery_geolocator (0.0.11)                        - Celery Geolocator
django-cms-storelocator (1.10.0)                  - A store locator extension for Django CMS
consul-locator (0.1.6)                            - python consul discovery locator for http
robotframework-selenium2library-divfor (1.8.0.1)  - Web testing library for Robot Framework with locator wrapper feature
django-storelocator (0.1)                         - Django Storelocator is a Django App for locating stores near a geographical location.
django-locator (1.0.0)                            - An easy to integrate store locator plugin for Django.
djangocms-store-locator (0.1.3)                   - A simple store locator django CMS plugin that uses Google Maps.
EditorConfig (0.12.1)                             - EditorConfig File Locator and Interpreter for Python
geolocator (0.1.1)                                - geolocator library: locate places and calculate distances between them
inmatelocator (0.0.8)                             - Library for locating people incarcerated in the US by querying official prison search tools
service-locator (0.1.3)                           - Dead simple python service locator
selenium-smart-locator (0.2.0)                    - A (somewhat) smart locator class for Selenium.
luogo (0.1.0)                                     - A service locator for python.
maidenhead (1.1.1)                                - Maidenhead Locator
mlocs (1.0.5)                                     - Effective Location Storage via a Maidenhead Locator System For Python
modulocator (0.1)                                 - Want to use a python module you're developing in you Jupyter notebook? Use modulocator to do that
osxrelocator (1.0.1)                              - Utility to relocate OSX libraries
pylisp (0.4.2)                                    - Locator/ID Separation Protocol (LISP) library
pylocator (1.0.beta.1.dev)                        - Program for the localization of EEG-electrodes.
relocator (0.1)                                   - change Location field in responses using WSGI middleware
solu (0.1)                                        - Self-service Office resource Locator and Updater
Task_allocator (1.0.2)                            - This program takes commandline input for the datafile from where configuration will be fetched.
ulp (1.1.1)                                       - ULP is a Locator Picker - a PathPicker clone for URLs
```

Please can you help me fix this?

**Comment by bozzmob** [comment]
I could solve #23 . So, I think this is ok. Will come back to this when needed.
