### ISSUE TITLE
FaceMorph error

### ISSUE THREAD

**Issue by singireddysravankumar** [alyssaq/face_morpher#26]
Hi i am new to python please can you tell me how to morph the images using commands in linux.
when i am using this command python facemorpher/morpher.py --src=index.jpg --dest=index3.jpg
Traceback (most recent call last):
  File "facemorpher/morpher.py", line 139, in <module>
    verify_args(args)
  File "facemorpher/morpher.py", line 42, in verify_args
    if args['/home/newter/face_morpher/images'] is None:
KeyError: '/home/newter/face_morpher/images'

thanks in advance

**Comment by alyssaq** [comment]
Hi. I cant reproduce the error. Are all the modules in requirements.txt installed?
If the images are present with a face, the command should work:
`python facemorpher/morpher.py --src=index.jpg --dest=index3.jpg`

**Comment by SagerMaeng** [comment]
Hi ,i am trying to
     python face_morpher/averager.py --src=16.jpg --dest=ted_cruz.jpg --out=a.png 
but,the result i received:
Usage:
    averager.py --images=<images_folder> [--blur] [--plot]
              [--background=(black|transparent|average)]
              [--width=<width>] [--height=<height>]
              [--out=<filename>] [--destimg=<filename>]
  Options:
    -h, --help             Show this screen.
    --images=<folder>      Folder to images (.jpg, .jpeg, .png)
    --blur                 Flag to blur edges of image [default: False]
    --width=<width>        Custom width of the images/video [default: 500]
    --height=<height>      Custom height of the images/video [default: 600]
    --out=<filename>       Filename to save the average face [default: result.png]
    --destimg=<filename>   Destination face image to overlay average face
    --plot                 Flag to display the average face [default: False]
    --background=<bg>      Background of image to be one of (black|transparent|average) [default: black]
    --version              Show version.
 there isn't a picture!
Thanks in advance

**Comment by SagerMaeng** [comment]
oh,no ,i admitted that i was  wrong ,but i corrected it ,the problem is the same.

**Comment by alyssaq** [comment]
Remove all the flags and only use `--images`.
E.g `python facemorpher/averager.py --images=images`
If theres are no face images, there will be no `result.png`
