### ISSUE TITLE
Exit status 127 - Installation Linux?

### ISSUE THREAD

**Issue by BLCKPSTV** [alyssaq/face_morpher#32]
Hey I installed this via pip as described also installed opencv with pip (no other explanation on this hub except for a mac installation (which also didn't work for me on my OSX) and a link to the opencv homepage...)

I'm getting this when running the example. Any idea? 

```
 python facemorpher/morpher.py --src=img440_0.jpg --dest=img963_0.jpg
/home/quinten/Documents/face_morpher/facemorpher/bin/stasm_util_linux_cv3: error while loading shared libraries: libopencv_calib3d.so.3.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "facemorpher/morpher.py", line 146, in <module>
    args['--alpha'], args['--plot'])
  File "facemorpher/morpher.py", line 130, in morpher
    src_img, src_points = next(images_points_gen)
  File "facemorpher/morpher.py", line 66, in load_valid_image_points
    img, points = load_image_points(path, size)
  File "facemorpher/morpher.py", line 56, in load_image_points
    points = locator.face_points(path)
  File "/home/quinten/Documents/face_morpher/facemorpher/locator.py", line 55, in face_points
    s = subprocess.check_output(command, universal_newlines=True)
  File "/home/quinten/anaconda2/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/quinten/Documents/face_morpher/facemorpher/bin/stasm_util_linux_cv3', '-f', '/home/quinten/Documents/face_morpher/facemorpher/data', 'img440_0.jpg']' returned non-zero exit status 127

```

**Comment by alyssaq** [comment]
What distro of Linux are you using? Unfortunately I dont have a linux machine and the stasm binaries were given to me by other contributors. You may have to rebuild stasm (face points locator) for your OS. I have the instructions written here: https://github.com/alyssaq/stasm_build

**Comment by BLCKPSTV** [comment]
I'll try the statsm_build tonight. And let you know!
