### ISSUE TITLE
stasm erro

### ISSUE THREAD

**Issue by orangelewis** [alyssaq/face_morpher#41]
Hi Alyssa,

I am trying to use the averager but I get the following error (MacOS 10.13.5 with python3.6.3):
Traceback (most recent call last):
  File "/Users/orangelewis/Spider/test.py", line 3, in <module>
    import stasm
  File "/Users/orangelewis/djiangoTest/lib/python3.6/site-packages/stasm/__init__.py", line 3, in <module>
    from _stasm import __doc__
ImportError: dlopen(/Users/orangelewis/djiangoTest/lib/python3.6/site-packages/_stasm.cpython-36m-darwin.so, 2): Symbol not found: __ZN2cv17CascadeClassifier16detectMultiScaleERKNS_11_InputArrayERSt6vectorINS_5Rect_IiEESaIS6_EEdiiNS_5Size_IiEESB_
  Referenced from: /Users/orangelewis/djiangoTest/lib/python3.6/site-packages/_stasm.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/orangelewis/djiangoTest/lib/python3.6/site-packages/_stasm.cpython-36m-darwin.so
Thank you!

**Comment by alyssaq** [comment]
What version of opencv are you running?  `import cv2; cv2.__version__`
Perhaps its not picking up the opencv libs. 
Could you run: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`

**Comment by alyssaq** [comment]
Hmm I have the same environment as your Mac but cant reproduce the error.
Glad it runs successfully on Windows!
