### ISSUE TITLE
[image not found] python3.7.2 and openCV 4.0.1 support

### ISSUE THREAD

**Issue by ShuchangXu** [alyssaq/face_morpher#49]
I tried the latest tutorial about installing openCV4 :
https://gist.github.com/alyssaq/f60393545173379e0f3f#file-4-opencv3-with-python3-md

And tried to morph from a source to destination image.

However, I got following error.
Does this have anything to do with my python3.7.2 and openCV4.0.1 version?
Thanks!

```
Traceback (most recent call last):
  File "facemorpher/morpher.py", line 34, in <module>
    from facemorpher import locator
  File "/Users/me/face_morpher/facemorpher/__init__.py", line 4, in <module>
    from .morpher import morpher, list_imgpaths
  File "/Users/me/face_morpher/facemorpher/morpher.py", line 34, in <module>
    from facemorpher import locator
  File "/Users/me/face_morpher/facemorpher/locator.py", line 7, in <module>
    import stasm
  File "/Users/me/.virtualenvs/py3/lib/python3.7/site-packages/stasm/__init__.py", line 3, in <module>
    from _stasm import __doc__
ImportError: dlopen(/Users/me/.virtualenvs/py3/lib/python3.7/site-packages/_stasm.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/opencv/lib/libopencv_core.3.4.dylib
  Referenced from: /Users/me/.virtualenvs/py3/lib/python3.7/site-packages/_stasm.cpython-37m-darwin.so
  Reason: image not found
```

**Comment by alyssaq** [comment]
Hi. Ive tried compiling stasm with openCV 4.0.1 but it simply doesnt work. At the moment, face morpher only works with openCV 3

**Comment by ShuchangXu** [comment]
Thanks! I will try to install openCV3
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/aaf45348653fc45674b7d798404f2cc9700e6f9c/Formula/opencv.rb`

**Comment by alyssaq** [comment]
Please try the new version using only dlib.

**Comment by kappaxbeta** [comment]
You also need to remove from locator.py the function "face_points_stasm" to avoid the import. Also I needed to set in morpher change the import "from facemorpher import $module" to just import $module
