### ISSUE TITLE
OpenCV Error using python facemorpher/morpher.py --src=1.jpg --dest=2.jpg --plot

### ISSUE THREAD

**Issue by mrgloom** [alyssaq/face_morpher#7]
`python facemorpher/morpher.py --src=1.jpg --dest=2.jpg --plot`

~~~
OpenCV Error: Assertion failed (points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S)) in boundingRect, file /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/contours.cpp, line 1895
Traceback (most recent call last):
  File "facemorpher/morpher.py", line 145, in <module>
    args['--alpha'], args['--plot'])
  File "facemorpher/morpher.py", line 130, in morpher
    src_img, src_points = images_points_gen.next()
  File "facemorpher/morpher.py", line 66, in load_valid_image_points
    img, points = load_image_points(path, size)
  File "facemorpher/morpher.py", line 56, in load_image_points
    points = locator.face_points(path)
  File "/home/user/Downloads/face_morpher/facemorpher/locator.py", line 41, in face_points
    points = np.vstack([points, boundary_points(points)])
  File "/home/user/Downloads/face_morpher/facemorpher/locator.py", line 16, in boundary_points
    x, y, w, h = cv2.boundingRect(np.array([points], np.int32))
cv2.error: /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/contours.cpp:1895: error: (-215) points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function boundingRect
~~~

**Comment by mrgloom** [comment]
Also

`python facemorpher/averager.py --images=/home/user/Downloads/face_morpher/imgs --out=average.png`

~~~
OpenCV Error: Assertion failed (points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S)) in boundingRect, file /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/contours.cpp, line 1895
Traceback (most recent call last):
  File "facemorpher/averager.py", line 94, in <module>
    args['--out'], args['--plot'])
  File "facemorpher/averager.py", line 61, in averager
    img, points = load_image_points(path, size)
  File "facemorpher/averager.py", line 47, in load_image_points
    points = locator.face_points(path)
  File "/home/user/Downloads/face_morpher/facemorpher/locator.py", line 41, in face_points
    points = np.vstack([points, boundary_points(points)])
  File "/home/user/Downloads/face_morpher/facemorpher/locator.py", line 16, in boundary_points
    x, y, w, h = cv2.boundingRect(np.array([points], np.int32))
cv2.error: /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/contours.cpp:1895: error: (-215) points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function boundingRect
~~~

**Comment by mrgloom** [comment]
False alarm, it works.

**Comment by edent** [comment]
How did you get this to work?
